set_global_assignment -name FAMILY "Cyclone III"
set_global_assignment -name DEVICE EP3C55F484C8
set_global_assignment -name RESERVE_ALL_UNUSED_PINS "AS INPUT TRI-STATED"
set_global_assignment -name RESERVE_ALL_UNUSED_PINS_NO_OUTPUT_GND "AS INPUT TRI-STATED"
set_global_assignment -name ENABLE_CLOCK_LATENCY ON
set_global_assignment -name CYCLONE_CONFIGURATION_DEVICE EPCS16
# system clock and reset----------------------------------------------------------------
set_location_assignment PIN_T2    -to sys_clk
set_location_assignment PIN_B11   -to reset_n
set_location_assignment PIN_A12   -to sys_clk1
set_location_assignment PIN_G21   -to sys_clk2
set_location_assignment PIN_G2    -to CLOCK0
set_location_assignment PIN_G22   -to CLOCK1
set_location_assignment PIN_A11   -to CLOCK2
set_location_assignment PIN_AB12  -to CLOCK3
# ddr sdram-----------------------------------------------------------------------------
set_location_assignment PIN_AA3   -to mem_clk
set_location_assignment PIN_AB3   -to mem_clk_n
set_location_assignment PIN_AB18  -to mem_addr[0]
set_location_assignment PIN_AB19  -to mem_addr[1]
set_location_assignment PIN_AB20  -to mem_addr[2]
set_location_assignment PIN_AA20  -to mem_addr[3]
set_location_assignment PIN_Y17   -to mem_addr[4]
set_location_assignment PIN_W17   -to mem_addr[5]
set_location_assignment PIN_Y15   -to mem_addr[6]
set_location_assignment PIN_Y14   -to mem_addr[7]
set_location_assignment PIN_AA15  -to mem_addr[8]
set_location_assignment PIN_AB15  -to mem_addr[9]
set_location_assignment PIN_AA17  -to mem_addr[10]
set_location_assignment PIN_AA14  -to mem_addr[11]
set_location_assignment PIN_AB14  -to mem_addr[12]
set_location_assignment PIN_Y3    -to mem_dq[0]
set_location_assignment PIN_W6    -to mem_dq[1]
set_location_assignment PIN_AA4   -to mem_dq[2]
set_location_assignment PIN_AA5   -to mem_dq[3]
set_location_assignment PIN_W7    -to mem_dq[4]
set_location_assignment PIN_Y7    -to mem_dq[5]
set_location_assignment PIN_U9    -to mem_dq[6]
set_location_assignment PIN_V8    -to mem_dq[7]
set_location_assignment PIN_AB7   -to mem_dq[8]
set_location_assignment PIN_Y8    -to mem_dq[9]
set_location_assignment PIN_U10   -to mem_dq[10]
set_location_assignment PIN_AA8   -to mem_dq[11]
set_location_assignment PIN_AB8   -to mem_dq[12]
set_location_assignment PIN_AA9   -to mem_dq[13]
set_location_assignment PIN_V11   -to mem_dq[14]
set_location_assignment PIN_W10   -to mem_dq[15]
set_location_assignment PIN_V10   -to mem_dqs[0]
set_location_assignment PIN_AB9   -to mem_dqs[1]
set_location_assignment PIN_V5    -to mem_dm[0]
set_location_assignment PIN_AA7   -to mem_dm[1]
set_location_assignment PIN_AA16  -to mem_ba[0]
set_location_assignment PIN_AB17  -to mem_ba[1]
set_location_assignment PIN_AB13  -to mem_cas_n
set_location_assignment PIN_AA13  -to mem_ras_n
set_location_assignment PIN_AB16  -to mem_cs_n
set_location_assignment PIN_AA19  -to mem_cke
set_location_assignment PIN_Y13   -to mem_we_n
# flash---------------------------------------------------------------------------------
set_location_assignment PIN_L22   -to Flash_A[1]
set_location_assignment PIN_K19   -to Flash_A[2]
set_location_assignment PIN_K18   -to Flash_A[3]
set_location_assignment PIN_M16   -to Flash_A[4]
set_location_assignment PIN_N16   -to Flash_A[5]
set_location_assignment PIN_N17   -to Flash_A[6]
set_location_assignment PIN_M19   -to Flash_A[7]
set_location_assignment PIN_M20   -to Flash_A[8]
set_location_assignment PIN_R18   -to Flash_A[9]
set_location_assignment PIN_T18   -to Flash_A[10]
set_location_assignment PIN_T17   -to Flash_A[11]
set_location_assignment PIN_T20   -to Flash_A[12]
set_location_assignment PIN_T19   -to Flash_A[13]
set_location_assignment PIN_U20   -to Flash_A[14]
set_location_assignment PIN_U19   -to Flash_A[15]
set_location_assignment PIN_W20   -to Flash_A[16]
set_location_assignment PIN_AA21  -to Flash_A[17]
set_location_assignment PIN_N19   -to Flash_A[18]
set_location_assignment PIN_N20   -to Flash_A[19]
set_location_assignment PIN_R19   -to Flash_A[20]
set_location_assignment PIN_R20   -to Flash_A[21]
set_location_assignment PIN_N18   -to Flash_A[22]
set_location_assignment PIN_W19   -to Flash_A[23]
set_location_assignment PIN_R17   -to Flash_A[24]
set_location_assignment PIN_M21   -to Flash_D[0]
set_location_assignment PIN_N21   -to Flash_D[1]
set_location_assignment PIN_P21   -to Flash_D[2]
set_location_assignment PIN_R21   -to Flash_D[3]
set_location_assignment PIN_U21   -to Flash_D[4]
set_location_assignment PIN_V21   -to Flash_D[5]
set_location_assignment PIN_W21   -to Flash_D[6]
set_location_assignment PIN_Y21   -to Flash_D[7]
set_location_assignment PIN_N22   -to Flash_D[8]
set_location_assignment PIN_P22   -to Flash_D[9]
set_location_assignment PIN_R22   -to Flash_D[10]
set_location_assignment PIN_U22   -to Flash_D[11]
set_location_assignment PIN_V22   -to Flash_D[12]
set_location_assignment PIN_W22   -to Flash_D[13]
set_location_assignment PIN_Y22   -to Flash_D[14]
set_location_assignment PIN_AA22  -to Flash_D[15]
set_location_assignment PIN_L21   -to Flash_nCS
set_location_assignment PIN_M22   -to Flash_nOE
set_location_assignment PIN_P20   -to Flash_nWE
# sram-----------------------------------------------------------------------------------
set_location_assignment PIN_D6    -to SRAM_A[0]
set_location_assignment PIN_E4    -to SRAM_A[1]
set_location_assignment PIN_E3    -to SRAM_A[2]
set_location_assignment PIN_G5    -to SRAM_A[3]
set_location_assignment PIN_G4    -to SRAM_A[4]
set_location_assignment PIN_R3    -to SRAM_A[5]
set_location_assignment PIN_R4    -to SRAM_A[6]
set_location_assignment PIN_T3    -to SRAM_A[7]
set_location_assignment PIN_T4    -to SRAM_A[8]
set_location_assignment PIN_T5    -to SRAM_A[9]
set_location_assignment PIN_AA2   -to SRAM_A[10]
set_location_assignment PIN_AA1   -to SRAM_A[11]
set_location_assignment PIN_Y2    -to SRAM_A[12]
set_location_assignment PIN_Y1    -to SRAM_A[13]
set_location_assignment PIN_W2    -to SRAM_A[14]
set_location_assignment PIN_M2    -to SRAM_A[15]
set_location_assignment PIN_M1    -to SRAM_A[16]
set_location_assignment PIN_M3    -to SRAM_A[17]
set_location_assignment PIN_W1    -to SRAM_A[18]
set_location_assignment PIN_H4    -to SRAM_D[0]
set_location_assignment PIN_J3    -to SRAM_D[1]
set_location_assignment PIN_J4    -to SRAM_D[2]
set_location_assignment PIN_H6    -to SRAM_D[3]
set_location_assignment PIN_L6    -to SRAM_D[4]
set_location_assignment PIN_N5    -to SRAM_D[5]
set_location_assignment PIN_P5    -to SRAM_D[6]
set_location_assignment PIN_P3    -to SRAM_D[7]
set_location_assignment PIN_V2    -to SRAM_D[8]
set_location_assignment PIN_V1    -to SRAM_D[9]
set_location_assignment PIN_U2    -to SRAM_D[10]
set_location_assignment PIN_U1    -to SRAM_D[11]
set_location_assignment PIN_J6    -to SRAM_D[12]
set_location_assignment PIN_R2    -to SRAM_D[13]
set_location_assignment PIN_R1    -to SRAM_D[14]
set_location_assignment PIN_P2    -to SRAM_D[15]
set_location_assignment PIN_H5    -to SRAM_nCS1
set_location_assignment PIN_G3    -to SRAM_nCS2
set_location_assignment PIN_N2    -to BYTE_ENABLE[1]
set_location_assignment PIN_P1    -to BYTE_ENABLE[0]
set_location_assignment PIN_P4    -to SRAM_nWE
set_location_assignment PIN_N1    -to SRAM_nOE
# nand flash----------------------------------------------------------------------------
set_location_assignment PIN_E1    -to NFlash_AD[0]
set_location_assignment PIN_F2    -to NFlash_AD[1]
set_location_assignment PIN_F1    -to NFlash_AD[2]
set_location_assignment PIN_J5    -to NFlash_AD[3]
set_location_assignment PIN_H2    -to NFlash_AD[4]
set_location_assignment PIN_H1    -to NFlash_AD[5]
set_location_assignment PIN_J1    -to NFlash_AD[6]
set_location_assignment PIN_J2    -to NFlash_AD[7]
set_location_assignment PIN_C2    -to NFlash_CLE
set_location_assignment PIN_B1    -to NFlash_nCS
set_location_assignment PIN_B12   -to NFlash_nRB
set_location_assignment PIN_B2    -to NFlash_nOE
set_location_assignment PIN_D2    -to NFlash_nWE
set_location_assignment PIN_C1    -to NFlash_ALE
# ext bus and lcd240x128----------------------------------------------------------------
set_location_assignment PIN_G8    -to D[0]
set_location_assignment PIN_H3    -to D[1]
set_location_assignment PIN_H7    -to D[2]
set_location_assignment PIN_J7    -to D[3]
set_location_assignment PIN_K7    -to D[4]
set_location_assignment PIN_N7    -to D[5]
set_location_assignment PIN_M6    -to D[6]
set_location_assignment PIN_M5    -to D[7]
set_location_assignment PIN_M4    -to D[8]
set_location_assignment PIN_N6    -to D[9]
set_location_assignment PIN_P7    -to D[10]
set_location_assignment PIN_P6    -to D[11]
set_location_assignment PIN_R5    -to D[12]
set_location_assignment PIN_R6    -to D[13]
set_location_assignment PIN_V4    -to D[14]
set_location_assignment PIN_V3    -to D[15]
set_location_assignment PIN_C10   -to A[0]
set_location_assignment PIN_E15   -to A[1]
set_location_assignment PIN_G14   -to A[2]
set_location_assignment PIN_F14   -to A[3]
set_location_assignment PIN_G13   -to A[4]
set_location_assignment PIN_G10   -to A[5]
set_location_assignment PIN_G11   -to A[6]
set_location_assignment PIN_G9    -to A[7]
set_location_assignment PIN_D7    -to A[8]
set_location_assignment PIN_C7    -to A[9]
set_location_assignment PIN_E7    -to A[10]
set_location_assignment PIN_C6    -to A[11]
set_location_assignment PIN_C4    -to A[12]
set_location_assignment PIN_C3    -to A[13]
set_location_assignment PIN_F11   -to A[14]
set_location_assignment PIN_F10   -to A[15]
set_location_assignment PIN_E9    -to A[16]
set_location_assignment PIN_F9    -to A[17]
set_location_assignment PIN_E8    -to A[18]
set_location_assignment PIN_F8    -to A[19]
set_location_assignment PIN_E6    -to A[20]
set_location_assignment PIN_F7    -to A[21]
set_location_assignment PIN_G7    -to A[22]
set_location_assignment PIN_C8    -to nWE
set_location_assignment PIN_F15   -to nOE
set_location_assignment PIN_C18   -to LCD_LIGHT
set_location_assignment PIN_D17   -to LCD_EN
set_location_assignment PIN_D13   -to EXT_BYTEEN[0]
set_location_assignment PIN_C13   -to EXT_BYTEEN[1]
# peripheral-----------------------------------------------------------------------------
set_location_assignment PIN_F13   -to ledout[0]
set_location_assignment PIN_D10   -to ledout[1]
set_location_assignment PIN_E10   -to ledout[2]
set_location_assignment PIN_D8    -to ledout[3]
set_location_assignment PIN_C17   -to ledout[4]
set_location_assignment PIN_E12   -to ledout[5]
set_location_assignment PIN_E13   -to ledout[6]
set_location_assignment PIN_E11   -to ledout[7]
set_location_assignment PIN_C15   -to I2C_SCL
set_location_assignment PIN_D15   -to I2C_SDA
set_location_assignment PIN_AB11  -to matrix_key_in[0]
set_location_assignment PIN_AA11  -to matrix_key_in[1]
set_location_assignment PIN_T21   -to matrix_key_in[2]
set_location_assignment PIN_T22   -to matrix_key_in[3]
set_location_assignment PIN_F16   -to matrix_key_out[0]
set_location_assignment PIN_F20   -to matrix_key_out[1]
set_location_assignment PIN_F19   -to matrix_key_out[2]
set_location_assignment PIN_C22   -to matrix_key_out[3]
set_location_assignment PIN_E16   -to BEEP
set_location_assignment PIN_H21   -to DcMotorSpeed
set_location_assignment PIN_H22   -to DcMotorA
set_location_assignment PIN_J21   -to DcMotorB
set_location_assignment PIN_J22   -to 8563_INT
set_location_assignment PIN_K22   -to LM75_OS
set_location_assignment PIN_D18   -to SEG[0]
set_location_assignment PIN_C19   -to SEG[1]
set_location_assignment PIN_D19   -to SEG[2]
set_location_assignment PIN_A20   -to SEG[3]
set_location_assignment PIN_C20   -to SEG[4]
set_location_assignment PIN_B21   -to SEG[5]
set_location_assignment PIN_B22   -to SEG[6]
set_location_assignment PIN_D20   -to SEG[7]
set_location_assignment PIN_C21   -to DIG[0]
set_location_assignment PIN_D22   -to DIG[1]
set_location_assignment PIN_D21   -to DIG[2]
set_location_assignment PIN_F17   -to DIG[3]
set_location_assignment PIN_H17   -to DIG[4]
set_location_assignment PIN_H16   -to DIG[5]
set_location_assignment PIN_J17   -to DIG[6]
set_location_assignment PIN_K17   -to DIG[7]
set_location_assignment PIN_E21   -to UART_RXD
set_location_assignment PIN_E22   -to UART_TXD
set_location_assignment PIN_G16   -to AD_CLK
set_location_assignment PIN_F22   -to AD_DAT
set_location_assignment PIN_K21   -to AD_NCS
set_location_assignment PIN_J18   -to DAC_LDAC
set_location_assignment PIN_H18   -to DAC_LOAD
set_location_assignment PIN_G17   -to DAC_DATA
set_location_assignment PIN_F21   -to DAC_CLK
set_location_assignment PIN_P17   -to StepMotor_PIO[0]
set_location_assignment PIN_G15   -to StepMotor_PIO[1]
set_location_assignment PIN_H19   -to StepMotor_PIO[2]
set_location_assignment PIN_G18   -to StepMotor_PIO[3]
set_location_assignment PIN_J20   -to IR_CLK
set_location_assignment PIN_J19   -to IR_TX
set_location_assignment PIN_H20   -to IR_RX
set_location_assignment PIN_AA12  -to 485_RO
set_location_assignment PIN_T1    -to USB_nINT
set_location_assignment PIN_G1    -to USB_VIN
# AD/DA PACK Pin-------------------------------------------------------------------------
set_location_assignment PIN_B5   -to PK1
set_location_assignment PIN_B20  -to PLL2_OUT
set_location_assignment PIN_A5   -to PK3
set_location_assignment PIN_B6   -to PK4
set_location_assignment PIN_A6   -to PK5
set_location_assignment PIN_B7   -to PK6
set_location_assignment PIN_A7   -to PK7
set_location_assignment PIN_B8   -to PK8
set_location_assignment PIN_B10  -to PK9
set_location_assignment PIN_A10  -to PK10
set_location_assignment PIN_B13  -to PK11
set_location_assignment PIN_A13  -to PK12
set_location_assignment PIN_B14  -to PK13
set_location_assignment PIN_A14  -to PK14
set_location_assignment PIN_B15  -to PK15
set_location_assignment PIN_B3   -to PA0
set_location_assignment PIN_A3   -to PA1
set_location_assignment PIN_B4   -to PA2
set_location_assignment PIN_A4   -to PA3
set_location_assignment PIN_A8   -to PA4
set_location_assignment PIN_B9   -to PA5
set_location_assignment PIN_A9   -to PA6
set_location_assignment PIN_A15  -to PA7
set_location_assignment PIN_B16  -to PA8
set_location_assignment PIN_A16  -to PA9
set_location_assignment PIN_B17  -to PA10
set_location_assignment PIN_A17  -to PA11
set_location_assignment PIN_B18  -to PA12
set_location_assignment PIN_A18  -to PA13
set_location_assignment PIN_B19  -to PA14
set_location_assignment PIN_A19  -to PA15
set_location_assignment PIN_E14  -to PA16
set_location_assignment PIN_E5   -to PLL3_OUT
# EXT25_IO Pin----------------------------------------------------------------------
set_location_assignment PIN_T16  -to EXT25_IO[0]
set_location_assignment PIN_T15  -to EXT25_IO[1]
set_location_assignment PIN_U15  -to EXT25_IO[2]
set_location_assignment PIN_U14  -to EXT25_IO[3]
set_location_assignment PIN_R16  -to EXT25_IO[4]
set_location_assignment PIN_U17  -to EXT25_IO[5]
set_location_assignment PIN_U16  -to EXT25_IO[6]
set_location_assignment PIN_V16  -to EXT25_IO[7]
set_location_assignment PIN_V15  -to EXT25_IO[8]
set_location_assignment PIN_W14  -to EXT25_IO[9]
set_location_assignment PIN_V14  -to EXT25_IO[10]
set_location_assignment PIN_W13  -to EXT25_IO[11]
set_location_assignment PIN_V13  -to EXT25_IO[12]
set_location_assignment PIN_U13  -to EXT25_IO[13]
set_location_assignment PIN_U12  -to EXT25_IO[14]
set_location_assignment PIN_T14  -to EXT25_IO[15]
set_location_assignment PIN_R14  -to EXT25_IO[16]
set_location_assignment PIN_R15  -to EXT25_IO[17]