# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fin.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 623)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../source/8b508045ce50657990e3afe7843944b8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 621, 591))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 13, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.LE_Sno_afr = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LE_Sno_afr.setObjectName("LE_Sno_afr")
        self.horizontalLayout_2.addWidget(self.LE_Sno_afr)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.LE_mon_afr = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LE_mon_afr.setObjectName("LE_mon_afr")
        self.horizontalLayout_2.addWidget(self.LE_mon_afr)
        self.B_afr = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.B_afr.setObjectName("B_afr")
        self.horizontalLayout_2.addWidget(self.B_afr)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 3)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 13, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.LE_Sno_search = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LE_Sno_search.setObjectName("LE_Sno_search")
        self.horizontalLayout.addWidget(self.LE_Sno_search)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.LE_Sname_search = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LE_Sname_search.setObjectName("LE_Sname_search")
        self.horizontalLayout.addWidget(self.LE_Sname_search)
        self.B_search = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.B_search.setObjectName("B_search")
        self.horizontalLayout.addWidget(self.B_search)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 3)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 13, -1)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.LE_MaTno_search = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LE_MaTno_search.setObjectName("LE_MaTno_search")
        self.horizontalLayout_3.addWidget(self.LE_MaTno_search)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.LE_MaTname_search = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.LE_MaTname_search.setObjectName("LE_MaTname_search")
        self.horizontalLayout_3.addWidget(self.LE_MaTname_search)
        self.B_MaT_search = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.B_MaT_search.setObjectName("B_MaT_search")
        self.horizontalLayout_3.addWidget(self.B_MaT_search)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 3)
        self.horizontalLayout_3.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Stu_info = QtWidgets.QWidget()
        self.Stu_info.setObjectName("Stu_info")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Stu_info)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 621, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TB_Stu_info = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.TB_Stu_info.setObjectName("TB_Stu_info")
        self.TB_Stu_info.setColumnCount(7)
        self.TB_Stu_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TB_Stu_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_Stu_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_Stu_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_Stu_info.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_Stu_info.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_Stu_info.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_Stu_info.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.TB_Stu_info)
        self.tabWidget.addTab(self.Stu_info, "")
        self.M_cost_tab = QtWidgets.QWidget()
        self.M_cost_tab.setObjectName("M_cost_tab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.M_cost_tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 621, 281))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TB_M_info = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.TB_M_info.setObjectName("TB_M_info")
        self.TB_M_info.setColumnCount(3)
        self.TB_M_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TB_M_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_M_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_M_info.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.TB_M_info)
        self.tabWidget.addTab(self.M_cost_tab, "")
        self.T_cost_tab = QtWidgets.QWidget()
        self.T_cost_tab.setObjectName("T_cost_tab")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.T_cost_tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(-1, -1, 621, 281))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TB_T_info = QtWidgets.QTableWidget(self.verticalLayoutWidget_4)
        self.TB_T_info.setObjectName("TB_T_info")
        self.TB_T_info.setColumnCount(3)
        self.TB_T_info.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TB_T_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_T_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TB_T_info.setHorizontalHeaderItem(2, item)
        self.verticalLayout_4.addWidget(self.TB_T_info)
        self.tabWidget.addTab(self.T_cost_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "财务系统"))
        self.label_4.setText(_translate("MainWindow", "~~~~~~~~~~~~~~~~~~~~~~~~~~~报销~~~~~~~~~~~~~~~~~~~~~~~~~~~"))
        self.label_5.setText(_translate("MainWindow", "学号"))
        self.label_6.setText(_translate("MainWindow", "报销金额"))
        self.B_afr.setText(_translate("MainWindow", "报销"))
        self.label.setText(_translate("MainWindow", "~~~~~~~~~~~~~~~~~~~~~~~~~~~查询~~~~~~~~~~~~~~~~~~~~~~~~~~~"))
        self.label_2.setText(_translate("MainWindow", "学号"))
        self.label_3.setText(_translate("MainWindow", "姓名"))
        self.B_search.setText(_translate("MainWindow", "学生查询"))
        self.label_7.setText(_translate("MainWindow", "编号"))
        self.label_8.setText(_translate("MainWindow", "名称"))
        self.B_MaT_search.setText(_translate("MainWindow", "药物查询"))
        item = self.TB_Stu_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "学号"))
        item = self.TB_Stu_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.TB_Stu_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "处方号"))
        item = self.TB_Stu_info.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "就诊日期"))
        item = self.TB_Stu_info.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "待缴费"))
        item = self.TB_Stu_info.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "已缴费用"))
        item = self.TB_Stu_info.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "报销金额"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Stu_info), _translate("MainWindow", "学生信息"))
        item = self.TB_M_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.TB_M_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.TB_M_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.M_cost_tab), _translate("MainWindow", "药物价格"))
        item = self.TB_T_info.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.TB_T_info.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.TB_T_info.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "价格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.T_cost_tab), _translate("MainWindow", "治疗价格"))


