# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pri.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../source/8b508045ce50657990e3afe7843944b8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 581, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(6, 0, 10, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.LE_MaTname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LE_MaTname.setObjectName("LE_MaTname")
        self.gridLayout.addWidget(self.LE_MaTname, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.LE_MaTno = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LE_MaTno.setObjectName("LE_MaTno")
        self.gridLayout.addWidget(self.LE_MaTno, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.B_MaT_CaA = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.B_MaT_CaA.setObjectName("B_MaT_CaA")
        self.gridLayout.addWidget(self.B_MaT_CaA, 1, 3, 1, 1)
        self.DSB_MaTpri = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.DSB_MaTpri.setMinimum(10.0)
        self.DSB_MaTpri.setMaximum(99999.99)
        self.DSB_MaTpri.setObjectName("DSB_MaTpri")
        self.gridLayout.addWidget(self.DSB_MaTpri, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 160, 581, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(19, 0, 8, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LB_no = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.LB_no.setAlignment(QtCore.Qt.AlignCenter)
        self.LB_no.setObjectName("LB_no")
        self.horizontalLayout.addWidget(self.LB_no)
        self.LE_no = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.LE_no.setObjectName("LE_no")
        self.horizontalLayout.addWidget(self.LE_no)
        self.LB_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.LB_name.setAlignment(QtCore.Qt.AlignCenter)
        self.LB_name.setObjectName("LB_name")
        self.horizontalLayout.addWidget(self.LB_name)
        self.LE_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.LE_name.setObjectName("LE_name")
        self.horizontalLayout.addWidget(self.LE_name)
        self.B_Search = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.B_Search.setObjectName("B_Search")
        self.horizontalLayout.addWidget(self.B_Search)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 3)
        self.horizontalLayout.setStretch(4, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 230, 481, 311))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(490, 230, 91, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.B_Payone = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.B_Payone.setObjectName("B_Payone")
        self.verticalLayout.addWidget(self.B_Payone)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 130, 586, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MODE_MaT = QtWidgets.QAction(MainWindow)
        self.MODE_MaT.setObjectName("MODE_MaT")
        self.MODE_pay = QtWidgets.QAction(MainWindow)
        self.MODE_pay.setObjectName("MODE_pay")
        self.menu.addAction(self.MODE_MaT)
        self.menu.addAction(self.MODE_pay)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "划价及缴费系统"))
        self.label_4.setText(_translate("MainWindow", "名称"))
        self.label_3.setText(_translate("MainWindow", "编号"))
        self.label_5.setText(_translate("MainWindow", "价格"))
        self.B_MaT_CaA.setText(_translate("MainWindow", "修改/添加"))
        self.LB_no.setText(_translate("MainWindow", "编号"))
        self.LB_name.setText(_translate("MainWindow", "名称"))
        self.B_Search.setText(_translate("MainWindow", "查询"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "价格"))
        self.B_Payone.setText(_translate("MainWindow", "缴费"))
        self.label_6.setText(_translate("MainWindow", "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"))
        self.menu.setTitle(_translate("MainWindow", "功能"))
        self.MODE_MaT.setText(_translate("MainWindow", "药物划价"))
        self.MODE_pay.setText(_translate("MainWindow", "学生缴费"))


