# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 550)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/8b508045ce50657990e3afe7843944b8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 200, 611, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 150, 611, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 0, 15, 2)
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Sno = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Sno.setObjectName("Sno")
        self.horizontalLayout.addWidget(self.Sno)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Sname = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.Sname.setObjectName("Sname")
        self.horizontalLayout.addWidget(self.Sname)
        self.Search = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search.setObjectName("Search")
        self.horizontalLayout.addWidget(self.Search)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 4)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 120, 611, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 80, 611, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 15, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.Age = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.Age.setProperty("value", 19)
        self.Age.setObjectName("Age")
        self.horizontalLayout_3.addWidget(self.Age)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.indent = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.indent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.indent.setObjectName("indent")
        self.indent.addItem("")
        self.indent.addItem("")
        self.horizontalLayout_3.addWidget(self.indent)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.MT = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.MT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MT.setObjectName("MT")
        self.MT.addItem("")
        self.MT.addItem("")
        self.MT.addItem("")
        self.horizontalLayout_3.addWidget(self.MT)
        self.Reg = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Reg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Reg.setObjectName("Reg")
        self.horizontalLayout_3.addWidget(self.Reg)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(5, 2)
        self.horizontalLayout_3.setStretch(6, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 611, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(5, 0, 14, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.Sno_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.Sno_2.setObjectName("Sno_2")
        self.horizontalLayout_2.addWidget(self.Sno_2)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.Sname_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.Sname_2.setObjectName("Sname_2")
        self.horizontalLayout_2.addWidget(self.Sname_2)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.collage = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.collage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.collage.setObjectName("collage")
        self.collage.addItem("")
        self.collage.addItem("")
        self.collage.addItem("")
        self.collage.addItem("")
        self.collage.addItem("")
        self.collage.addItem("")
        self.collage.addItem("")
        self.collage.addItem("")
        self.collage.addItem("")
        self.horizontalLayout_2.addWidget(self.collage)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 3)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 3)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 611, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 612, 28))
        self.menuBar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setStatusTip("")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStatusTip("")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.Stu_info = QtWidgets.QAction(MainWindow)
        self.Stu_info.setObjectName("Stu_info")
        self.Stu_reg = QtWidgets.QAction(MainWindow)
        self.Stu_reg.setObjectName("Stu_reg")
        self.reg = QtWidgets.QAction(MainWindow)
        self.reg.setObjectName("reg")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menu.addSeparator()
        self.menu.addAction(self.Stu_info)
        self.menu.addAction(self.Stu_reg)
        self.menu.addAction(self.actionexit)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.actionexit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "挂号系统"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "学号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "年龄"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "学院"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "学生类型"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "医保类型"))
        self.label.setText(_translate("MainWindow", "学号"))
        self.label_2.setText(_translate("MainWindow", "姓名"))
        self.Search.setText(_translate("MainWindow", "查询"))
        self.label_3.setText(_translate("MainWindow", "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~查询~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"))
        self.label_6.setText(_translate("MainWindow", "年龄"))
        self.label_7.setText(_translate("MainWindow", "学生类型"))
        self.indent.setItemText(0, _translate("MainWindow", "本科生"))
        self.indent.setItemText(1, _translate("MainWindow", "研究生"))
        self.label_9.setText(_translate("MainWindow", "医保类型"))
        self.MT.setItemText(0, _translate("MainWindow", "城镇居民"))
        self.MT.setItemText(1, _translate("MainWindow", "城镇职工"))
        self.MT.setItemText(2, _translate("MainWindow", "新农合"))
        self.Reg.setText(_translate("MainWindow", "挂号"))
        self.label_5.setText(_translate("MainWindow", "学号"))
        self.label_4.setText(_translate("MainWindow", "姓名"))
        self.label_8.setText(_translate("MainWindow", "学院"))
        self.collage.setItemText(0, _translate("MainWindow", "自动化院"))
        self.collage.setItemText(1, _translate("MainWindow", "医学院"))
        self.collage.setItemText(2, _translate("MainWindow", "法学院"))
        self.collage.setItemText(3, _translate("MainWindow", "计算机院"))
        self.collage.setItemText(4, _translate("MainWindow", "药学院"))
        self.collage.setItemText(5, _translate("MainWindow", "地信院"))
        self.collage.setItemText(6, _translate("MainWindow", "机电院"))
        self.collage.setItemText(7, _translate("MainWindow", "化工院"))
        self.collage.setItemText(8, _translate("MainWindow", "资安院"))
        self.label_10.setText(_translate("MainWindow", "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~挂号~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"))
        self.menu.setToolTip(_translate("MainWindow", "菜单"))
        self.menu.setTitle(_translate("MainWindow", "查询方式"))
        self.Stu_info.setText(_translate("MainWindow", "学生个人信息"))
        self.Stu_reg.setText(_translate("MainWindow", "学生就诊信息"))
        self.reg.setText(_translate("MainWindow", "reg"))
        self.actionexit.setText(_translate("MainWindow", "退出"))


